### ISSUE TITLE
第一次建档输入姓名后闪退

### ISSUE THREAD

**Issue by im20A0** [Godofcong-1/erArk#11]
Traceback (most recent call last):
  File "/home/im20a0/erArk/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File "/home/im20a0/erArk/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File "/home/im20a0/erArk/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "/home/im20a0/erArk/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "/home/im20a0/erArk/Script/UI/Flow/creator_character_flow.py", line 41, in creator_character_panel
    game_start()
  File "/home/im20a0/erArk/Script/UI/Flow/creator_character_flow.py", line 51, in game_start
    character_handle.init_character_position()
  File "/home/im20a0/erArk/Script/Design/character_handle.py", line 192, in init_character_position
    map_handle.character_move_scene(character_position, character_dormitory, character_id)
  File "/home/im20a0/erArk/Script/Design/map_handle.py", line 93, in character_move_scene
    if character_id in cache.scene_data[old_scene_path_str].character_list:
KeyError: '0/0'

**Comment by im20A0** [comment]
载入Wine打开exe存的档依然闪退
Traceback (most recent call last):
  File "/home/im20a0/erArk/erArk/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File "/home/im20a0/erArk/erArk/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File "/home/im20a0/erArk/erArk/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "/home/im20a0/erArk/erArk/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "/home/im20a0/erArk/erArk/Script/UI/Flow/normal_flow.py", line 31, in in_scene_flow
    now_panel.draw()
  File "/home/im20a0/erArk/erArk/Script/UI/Panel/in_scene_panel.py", line 48, in draw
    scene_data: game_type.Scene = cache.scene_data[scene_path_str]
KeyError: '中枢/博士房间'

**Comment by im20A0** [comment]
还有一个怪问题，只有建档第一天干员的行动是正常的，其他时候都会昏昏欲睡，不断跑到宿舍睡觉，也因为太困无法跟随，但去宿舍看他们的体力是满的

**Comment by Godofcong-1** [comment]
草竟然真的有人的吗，前段时间的版本有好几个就是写到BUG寄了先存一下找找思路，你可能不小心玩到了某一个。今天刚push了个新的，这个大概没问题（大概）。
以及干员AI现在还只搭了个框架，所以有bug（点头）。你的bug八成是因为干员们没完成睡觉动作，完成了的话会清除疲惫状态，有疲惫状态就没法跟随得回去睡觉，可能是我睡觉判定没写好 @im20A0
