### ISSUE TITLE
有人在的时候休息就闪退

### ISSUE THREAD

**Issue by wokeshilolik** [Godofcong-1/erArk#16]
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 50, in init
  File "Script\Core\game_init.py", line 42, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 38, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 339, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 511, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 86, in handle_rest
  File "Script\Design\update.py", line 16, in game_update_flow
  File "Script\Design\character_behavior.py", line 67, in init_character_behavior
  File "Script\Design\character_behavior.py", line 181, in character_behavior
  File "Script\Design\character_behavior.py", line 375, in judge_character_status
  File "Script\Design\settle_behavior.py", line 34, in handle_settle_behavior
  File "Script\Design\settle_behavior.py", line 406, in change_character_value_add_as_time
UnboundLocalError: local variable 'add_tired' referenced before assignment
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 50, in init
  File "Script\Core\game_init.py", line 42, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 38, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 339, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 511, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 86, in handle_rest
  File "Script\Design\update.py", line 16, in game_update_flow
  File "Script\Design\character_behavior.py", line 67, in init_character_behavior
  File "Script\Design\character_behavior.py", line 150, in character_behavior
  File "Script\Design\character_behavior.py", line 788, in character_aotu_change_value
  File "Script\Design\character_behavior.py", line 375, in judge_character_status
  File "Script\Design\settle_behavior.py", line 34, in handle_settle_behavior
  File "Script\Design\settle_behavior.py", line 406, in change_character_value_add_as_time
UnboundLocalError: local variable 'add_tired' referenced before assignment
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 50, in init
  File "Script\Core\game_init.py", line 42, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 38, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 339, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 511, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 86, in handle_rest
  File "Script\Design\update.py", line 16, in game_update_flow
  File "Script\Design\character_behavior.py", line 67, in init_character_behavior
  File "Script\Design\character_behavior.py", line 150, in character_behavior
  File "Script\Design\character_behavior.py", line 788, in character_aotu_change_value
  File "Script\Design\character_behavior.py", line 375, in judge_character_status
  File "Script\Design\settle_behavior.py", line 34, in handle_settle_behavior
  File "Script\Design\settle_behavior.py", line 406, in change_character_value_add_as_time
UnboundLocalError: local variable 'add_tired' referenced before assignment
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 50, in init
  File "Script\Core\game_init.py", line 42, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 38, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 339, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 511, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 208, in handle_owner_abl_up
  File "Script\UI\Panel\see_character_info_panel.py", line 2609, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\see_character_info_panel.py", line 1260, in draw
KeyError: 9
进游戏一两分钟就闪退，感觉每一个操作都如覆薄冰。还有属性上升也特别容易闪退

**Comment by Godofcong-1** [comment]
@wokeshilolik 感谢报bug，今天推的版本已修复这两个bug（理论上）。目前还只在做开发，完全没有做过bug测试工作，如履薄冰这个词连我都觉得用得好√
