### ISSUE TITLE
输入名字点击开始后闪退

### ISSUE THREAD

**Issue by cz2h** [Godofcong-1/erArk#17]
输入博士名字后点击开始， 游戏闪退。

**Comment by cz2h** [comment]
log 如下

Traceback (most recent call last):
  File " erArk/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File " erArk/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File " erArk/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File " erArk/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File " erArk/Script/UI/Flow/creator_character_flow.py", line 47, in creator_character_panel
    game_start()
  File " erArk/Script/UI/Flow/creator_character_flow.py", line 60, in game_start
    character_handle.init_character_position()
  File " erArk/Script/Design/character_handle.py", line 274, in init_character_position
    map_handle.character_move_scene(character_position, character_dormitory, character_id)
  File " erArk/Script/Design/map_handle.py", line 97, in character_move_scene
    if character_id in cache.scene_data[old_scene_path_str].character_list:
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: '0/0'
Traceback (most recent call last):
  File " erArk/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File " erArk/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File " erArk/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File " erArk/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File " erArk/Script/UI/Flow/creator_character_flow.py", line 47, in creator_character_panel
    game_start()
  File " erArk/Script/UI/Flow/creator_character_flow.py", line 60, in game_start
    character_handle.init_character_position()
  File " erArk/Script/Design/character_handle.py", line 274, in init_character_position
    map_handle.character_move_scene(character_position, character_dormitory, character_id)
  File " erArk/Script/Design/map_handle.py", line 97, in character_move_scene
    if character_id in cache.scene_data[old_scene_path_str].character_list:
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: '0/0'
Traceback (most recent call last):
  File " erArk/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File " erArk/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File " erArk/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File " erArk/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File " erArk/Script/UI/Flow/creator_character_flow.py", line 47, in creator_character_panel
    game_start()
  File " erArk/Script/UI/Flow/creator_character_flow.py", line 60, in game_start
    character_handle.init_character_position()
  File " erArk/Script/Design/character_handle.py", line 274, in init_character_position
    map_handle.character_move_scene(character_position, character_dormitory, character_id)
  File " erArk/Script/Design/map_handle.py", line 97, in character_move_scene
    if character_id in cache.scene_data[old_scene_path_str].character_list:
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: '0/0'
Traceback (most recent call last):
  File " erArk/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File " erArk/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File " erArk/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File " erArk/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File " erArk/Script/UI/Flow/creator_character_flow.py", line 47, in creator_character_panel
    game_start()
  File " erArk/Script/UI/Flow/creator_character_flow.py", line 60, in game_start
    character_handle.init_character_position()
  File " erArk/Script/Design/character_handle.py", line 274, in init_character_position
    map_handle.character_move_scene(character_position, character_dormitory, character_id)
  File " erArk/Script/Design/map_handle.py", line 97, in character_move_scene
    if character_id in cache.scene_data[old_scene_path_str].character_list:
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: '0/0'
Traceback (most recent call last):
  File " erArk/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File " erArk/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File " erArk/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File " erArk/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File " erArk/Script/UI/Flow/creator_character_flow.py", line 47, in creator_character_panel
    game_start()
  File " erArk/Script/UI/Flow/creator_character_flow.py", line 60, in game_start
    character_handle.init_character_position()
  File " erArk/Script/Design/character_handle.py", line 274, in init_character_position
    map_handle.character_move_scene(character_position, character_dormitory, character_id)
  File " erArk/Script/Design/map_handle.py", line 97, in character_move_scene
    if character_id in cache.scene_data[old_scene_path_str].character_list:
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: '0/0'

**Comment by Godofcong-1** [comment]
请问是哪个版本？我这边测试还没遇到过这种bug，我看看怎么复现

**Comment by cz2h** [comment]
> 请问是哪个版本？我这边测试还没遇到过这种bug，我看看怎么复现

用的直接是master branch 这个版本， python 用的是Python 3.11.4。 

麻烦大兄弟了

**Comment by cz2h** [comment]
> 我本地的是py3.9.16，不过只要库装对了应该不是py版本的问题。你试试Releases里打包好的？

大兄弟你好， 我觉得问题应该出在 'map_config.py::31'， scenedata 里面的key 用的是 \\ 作为分隔， 但是macos 和Linux之类的用的是/ 。 所以在后续会出现key error 的情况 （key ‘0/0’ not in dict where dict has key ‘0\\0’）。

或许可以考虑把预处理scenedata 相关的逻辑分离出来？

**Comment by Godofcong-1** [comment]
> 
> 大兄弟你好， 我觉得问题应该出在 'map_config.py::31'， scenedata 里面的key 用的是 \ 作为分隔， 但是macos 和Linux之类的用的是/ 。 所以在后续会出现key error 的情况 （key ‘0/0’ not in dict where dict has key ‘0\0’）。
> 
> 把data 下面的file 删掉， 等map cofig 重新生成一遍就没事了

噢，原来是操作系统的问题。这游戏原来还可以在非win里玩的吗（震惊我自己）
