### ISSUE TITLE
随机触发错误

### ISSUE THREAD

**Issue by A1ca7raz** [Godofcong-1/erArk#18]
```
Traceback (most recent call last):
  File "/.../erArk-git/Script/Core/game_init.py", line 50, in init
    run_main_flow()
  File "/.../erArk-git/Script/Core/game_init.py", line 42, in run_main_flow
    main_flow()
  File "/.../erArk-git/Script/Design/start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "/.../erArk-git/Script/Design/handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "/.../erArk-git/Script/UI/Flow/normal_flow.py", line 122, in see_map_flow
    now_panel.draw()
  File "/.../erArk-git/Script/UI/Panel/see_map_panel.py", line 182, in draw
    yrn = flow_handle.askfor_all(return_list)
  File "/.../erArk-git/Script/Core/flow_handle.py", line 274, in askfor_all
    _cmd_deal(order)
  File "/.../erArk-git/Script/Core/flow_handle.py", line 191, in _cmd_deal
    cmd_map[order_number]()
  File "/.../erArk-git/Script/Core/flow_handle.py", line 118, in run_func
    cmd_func(*arg, **kw)
  File "/.../erArk-git/Script/UI/Panel/see_map_panel.py", line 215, in move_now
    character_move.own_charcter_move(scene_path)
  File "/.../erArk-git/Script/Design/character_move.py", line 40, in own_charcter_move
    update.game_update_flow(now_need_time)
  File "/.../erArk-git/Script/Design/update.py", line 15, in game_update_flow
    character_behavior.init_character_behavior()
  File "/.../erArk-git/Script/Design/character_behavior.py", line 63, in init_character_behavior
    character_behavior(character_id, cache.game_time)
  File "/.../erArk-git/Script/Design/character_behavior.py", line 199, in character_behavior
    find_character_target(character_id, now_time)
  File "/.../erArk-git/Script/Design/character_behavior.py", line 254, in find_character_target
    constant.handle_state_machine_data[state_machine_id](character_id)
  File "/.../erArk-git/Script/Design/handle_state_machine.py", line 27, in return_wrapper
    return func(*args, **kwargs)
  File "/.../erArk-git/Script/StateMachine/default.py", line 786, in character_move_to_bathzone_locker_room
    general_movement_module(character_id, to_locker_room)
UnboundLocalError: local variable 'to_locker_room' referenced before assignment
```

**Comment by Godofcong-1** [comment]
因为长时间没有回复，所以我姑且先把它关掉了
