### ISSUE TITLE
2023.11.23版本，进行操作频繁报错

### ISSUE THREAD

**Issue by YGHOUT** [Godofcong-1/erArk#20]
和角色聊天是一定会报错的。

版本信息：Past.2023.11.23
最近输入指令：['81', '\n0', '[000]经常看到的部位字母缩写分别代表什么意思？', '[001]刻印是什么东西？有什么用？如何获得或消除？', '返回', '\n1', '[000]干员每天的日常行动是什么样的？', '返回', '\n2', '[000]如何和干员处好关系？', '[001]惹干员生气了怎么办？', '返回', '\n3', '[000]如何才能与干员H？', '[001]如何用道具来H？', '[002]干员会怀孕吗？可以真的生出小孩吗？', '返回', '返回', '44', '返回', '66']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 40, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 343, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 515, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 1873, in handle_official_work
  File "Script\Design\update.py", line 15, in game_update_flow
  File "Script\Design\character_behavior.py", line 66, in init_character_behavior
  File "Script\Design\character_behavior.py", line 168, in character_behavior
  File "Script\Design\character_behavior.py", line 351, in judge_character_status
  File "Script\Design\talk.py", line 65, in handle_talk
KeyError: 'in_dorm'

版本信息：Past.2023.11.23
最近输入指令：['\n2', '[000]如何和干员处好关系？', '[001]惹干员生气了怎么办？', '返回', '\n3', '[000]如何才能与干员H？', '[001]如何用道具来H？', '[002]干员会怀孕吗？可以真的生出小孩吗？', '返回', '返回', '44', '返回', '66', '0', '0', '0', 'x', '0', '25', '0', '博士办公室']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 124, in see_map_flow
  File "Script\UI\Panel\see_map_panel.py", line 200, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\see_map_panel.py", line 233, in move_now
  File "Script\Design\character_move.py", line 40, in own_charcter_move
  File "Script\Design\update.py", line 15, in game_update_flow
  File "Script\Design\character_behavior.py", line 66, in init_character_behavior
  File "Script\Design\character_behavior.py", line 168, in character_behavior
  File "Script\Design\character_behavior.py", line 351, in judge_character_status
  File "Script\Design\talk.py", line 65, in handle_talk
KeyError: 'in_dorm'

**Comment by Godofcong-1** [comment]
感谢报错，经检查是对话地文里的前提名字打错了，新版本已修正，如有其他问题欢迎再反馈
