### ISSUE TITLE
Crash - 人员招募>工位调整

### ISSUE THREAD

**Issue by TheXeler** [Godofcong-1/erArk#22]
版本信息：2023.12.30
最近输入指令：['启动资金', '0', '娱乐', '娱乐', '娱乐', '娱乐', '44', '返回', '4', '0', '1', '0', '10', '→文职办公部入口', '90', '0', '→人事办公室', '71', '73', '[002]工位调整', '确定']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 198, in recruit_flow
  File "Script\UI\Panel\recruit_panel.py", line 136, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\recruit_panel.py", line 301, in select_npc_position
  File "Script\Design\basement.py", line 133, in get_base_updata
KeyError: -1

**Comment by Godofcong-1** [comment]
感谢反馈，检查发现是如果在没有选择工位调整角色的情况下点击确定键，就会因为角色序号为-1导致报错，已修正
