### ISSUE TITLE
Crash - 助理设置

### ISSUE THREAD

**Issue by TheXeler** [Godofcong-1/erArk#23]
版本信息：2023.12.30
最近输入指令：['返回', '4', '0', '1', '0', '10', '→文职办公部入口', '0', '→人事办公室', '71', '71', '71', '0', '10', '→控制中枢入口', '0', '→博士办公室', '4', '1', '77', '[009]性处理服务(未实装)    否']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 48, in assistant_flow
  File "Script\UI\Panel\assistant_panel.py", line 146, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\assistant_panel.py", line 193, in chose_button
  File "Script\UI\Panel\assistant_panel.py", line 203, in settlement_of_associated_attribute
KeyError: 9

**Comment by Godofcong-1** [comment]
感谢反馈，该按钮将不会绘制，等该功能实装后再绘制
