### ISSUE TITLE
Crash - 源石技艺>触觉系能力

### ISSUE THREAD

**Issue by TheXeler** [Godofcong-1/erArk#24]
版本信息：2023.12.30
最近输入指令：['0', '娱乐', '娱乐', '娱乐', '娱乐', '44', '返回', '4', '0', '1', '3', '11', '返回', '返回', '9', '11', '\n玩家属性', '\n8', '返回', '3', '7']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 186, in originium_arts_flow
  File "Script\UI\Panel\originium_arts.py", line 187, in draw
KeyError: 7

**Comment by Godofcong-1** [comment]
感谢反馈，经检查发现是触觉系的按钮错误地绑定到了改变催眠类型功能上，已修正
