### ISSUE TITLE
Crash - 人事办公室>选择招募后崩溃

### ISSUE THREAD

**Issue by TheXeler** [Godofcong-1/erArk#26]
版本信息：2023.12.31
最近输入指令：['0', '1', '返回', '95', '0', '2', '→控制中枢入口', '0', '11', '4', '1', '0', '10', '文职', '10', '22', '0', '→人事办公室', '73', '[002]工位调整', ' [选择该招募] _0']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 198, in recruit_flow
  File "Script\UI\Panel\recruit_panel.py", line 136, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\recruit_panel.py", line 301, in select_npc_position
UnboundLocalError: local variable 'yes_draw' referenced before assignment

**Comment by Godofcong-1** [comment]
感谢反馈，经检查该按钮的功能函数绑定错误，已重新修正为[将选择专员调整至该招募]按钮与对应函数
