### ISSUE TITLE
Crash - 制造加工区>工位调整参数为空时崩溃

### ISSUE THREAD

**Issue by TheXeler** [Godofcong-1/erArk#27]
版本信息：2023.12.31
最近输入指令：['[002]工位调整', '返回', '返回', '0', '10', '→制造加工区入口', '0', '→生产车间1', '83', ' [生产调整] _0', '\n3', ' [生产调整] _1', '\n3', ' [生产调整] _2', '\n3', ' [生产调整] _3', '\n3', '[001]工人增减', '返回', '[002]工位调整', '确定']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 41, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 343, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 517, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 377, in handle_manage_library
  File "Script\UI\Panel\manage_assembly_line_panel.py", line 173, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\manage_assembly_line_panel.py", line 370, in select_npc_position
  File "Script\Design\basement.py", line 155, in get_base_updata
KeyError: -1

**Comment by Godofcong-1** [comment]
感谢反馈，和招募同款BUG，已修正
