### ISSUE TITLE
Crash - 导航后崩溃

### ISSUE THREAD

**Issue by TheXeler** [Godofcong-1/erArk#29]
版本信息：2023.12.31
最近输入指令：['\n【升级】', '访客区', '返回', '返回', '0', '12', '→访客区入口', '0', '→外交办公室', '4', '4', '0', '19', '→控制中枢入口', '0', '→指挥室', '67', '67', '67', '85', '→东']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 41, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 343, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 517, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 406, in handle_navigation
  File "Script\UI\Panel\navigation_panel.py", line 212, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\navigation_panel.py", line 44, in move_judge
TypeError: '<=' not supported between instances of 'int' and 'str'

**Comment by Godofcong-1** [comment]
感谢反馈，经检查，该BUG是因为导航面板中下方的快捷移动按钮参数传递错误，已修正
