### ISSUE TITLE
Crash - 有点棘手的新崩溃报告

### ISSUE THREAD

**Issue by TheXeler** [Godofcong-1/erArk#32]
版本信息：2023.12.31-AlphaRefix
最近输入指令：['10', '中枢', '10', '22', '0', '博士房间', '23', '24', ' [8小时] ', '确定\n\n', '0', '10', '文职', '10', '22', '0', '10', '22', '0', '办公室', '71']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 41, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 262, in draw
  File "Script\UI\Panel\see_character_info_panel.py", line 428, in __init__
IndexError: list index out of range
复现存档：
[4.zip](https://github.com/Godofcong-1/erArk/files/13800967/4.zip)
复现方式：招募干员
附注：好像是多萝西的问题，我点她头像也会崩溃

**Comment by TheXeler** [comment]
追加报告：
版本信息：2023.12.31-AlphaRefix
最近输入指令：['23', '11', '73', '[001]人员增减', '返回', '[001]人员增减', '返回', '返回', '39', '39', '39', '39', '39', '特蕾西娅头像', '鸿雪头像', '特蕾西娅头像', '71', '歌蕾蒂娅头像', '特蕾西娅头像', '鸿雪头像', '杜宾头像']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 41, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 262, in draw
  File "Script\UI\Panel\see_character_info_panel.py", line 428, in __init__
IndexError: list index out of range
附录：杜宾怎么也会触发了，好怪

**Comment by Godofcong-1** [comment]
感谢反馈，检查了一下代码和存档数据，这里报错应该是因为某种原因导致角色的衣服的脏污数据为空，所以出现的报错。
这块的代码我加了以以下检测是否为空的判断机制，不过只是治标的办法，治本还是需要探明为什么会为空，以下是几种可能的原因，你看看哪个最近发生过：①在角色洗澡的时候对角色在衣柜里的衣服射精过，②在猥亵或H中对角色穿在身上的衣服射精过，③把角色的内裤或袜子脱下来后拿来射精过
我能猜得到的应该是这三种情况会有衣服射精的判定，如果都不是的话……那我得再多寻思寻思

**Comment by TheXeler** [comment]
没有，这个档我还是处（含自行发电），你看我个人信息应该可以看到
有没有可能是大浴场换浴巾或者类似情况导致的（干员自行更换衣服导致）

**Comment by Godofcong-1** [comment]
换衣服的情况就比较多了，可能比较难排查……总之我在疑似情况里也加了一些判定，看看以后还会不会出现吧
