### ISSUE TITLE
Crash - 升级EX级技能会导致崩溃

### ISSUE THREAD

**Issue by TheXeler** [Godofcong-1/erArk#33]
版本信息：2023.12.31-AlphaRefix
最近输入指令：['Ｎ感觉', '返回', '亲密', '确定', '亲密', '确定', '亲密', '确定', '亲密', '确定', '亲密', '确定', '亲密', '确定', '亲密', '确定', '话术技能', '返回', '亲密', '确定', '亲密']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 41, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 343, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 517, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 210, in handle_owner_abl_up
  File "Script\UI\Panel\ability_up_panel.py", line 439, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\ability_up_panel.py", line 141, in draw
KeyError: 8
附注：这种定位精确的BUG我不提供存档应该也不成问题吧.jpg

**Comment by Godofcong-1** [comment]
感谢反馈，已限制在EX级之后无法再进行升级
