### ISSUE TITLE
验算行为故障

### ISSUE THREAD

**Issue by geniusgd24** [Godofcong-1/erArk#37]
版本信息：2024.2.16
最近输入指令：['15', '15', '93', '131', '0', '238', '0', '返回', '7', '返回', '146', '145', '144', '139', '140', '140', '163', '152', '159', '148', '211']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 42, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 344, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 518, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 4227, in handle_face_seat_sex
  File "Script\Design\character.py", line 299, in calculation_instuct_judege
TypeError: cannot unpack non-iterable NoneType object

雷蛇，好感度3万信赖度300，这使得大部分需要验算的行动出故障（可能是数值太高了，麻烦看一看）

其他人（暂时）没问题

**Comment by Godofcong-1** [comment]
感谢反馈，经检查当超过300信赖时会出现无法判定当前信赖等级的BUG，已经通过限制最大值和完善判定函数逻辑的方式修复了该BUG，新版本已推送，如仍有类似问题欢迎随时反馈
