### ISSUE TITLE
食铁兽生育崩溃

### ISSUE THREAD

**Issue by KUROTO-DAN** [Godofcong-1/erArk#38]
版本信息：2024.2.23
最近输入指令：['1', '15', '15', '15', '15', '15', '15', '15', '15', '15', '15', '15', '4', '0', '1', '27', ' [8小时] ', ' [关门] ', '确定\n\n', '\n', 'C']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 42, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 317, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 520, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 635, in handle_sleep
  File "Script\UI\Panel\normal_panel.py", line 470, in draw
  File "Script\Design\update.py", line 15, in game_update_flow
  File "Script\Design\character_behavior.py", line 61, in init_character_behavior
  File "Script\Design\character_behavior.py", line 150, in character_behavior
  File "Script\Design\character_behavior.py", line 733, in update_sleep
  File "Script\Design\pregnancy.py", line 351, in check_all_pregnancy
  File "Script\Design\pregnancy.py", line 204, in check_born
  File "Script\UI\Panel\sp_event_panel.py", line 111, in draw
  File "Script\Design\character_handle.py", line 169, in born_new_character
  File "Script\Design\character_handle.py", line 97, in init_character
  File "Script\Design\character.py", line 50, in init_attr
  File "Script\Design\attr_calculation.py", line 224, in get_action_info_state_zero
  File "Script\Design\game_time.py", line 198, in get_sub_date
ValueError: day is out of range for month
复现存档：
[1.zip](https://github.com/Godofcong-1/erArk/files/14390426/1.zip)

附注：有个女儿在博士办公室成为了地缚灵，耗光体力当场回满，最草的是，她甚至是办公室招募过来的。

**Comment by Godofcong-1** [comment]
感谢反馈，检查了一下发现是创建初始角色的属性的时候，日期在月份上出现错误的BUG，已修复
地缚灵（草）的女儿是哪个

**Comment by KUROTO-DAN** [comment]
屑奸商的女儿，她被死缚在博士办公室，就算调整干员岗位也调不走。

**Comment by Godofcong-1** [comment]
现在的新版本里，日期BUG、地缚灵BUG和食物BUG都好了吗

**Comment by KUROTO-DAN** [comment]
更新：用2.26测试了一下了，相同問題
版本信息：2024.2.26
最近输入指令：['塞雷娅头像', '1', '返回', '4', '0', '1', '15', '15', '15', '15', '15', '15', '15', '15', '15', '15', '15', '4', '0', '1', '24']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 91, in food_bag_flow
  File "Script\UI\Panel\food_bag_panel.py", line 64, in draw
  File "Script\UI\Moudle\panel.py", line 685, in update
  File "Script\UI\Panel\food_bag_panel.py", line 197, in __init__
AttributeError: 'Food' object has no attribute 'milk_ml'

**Comment by Godofcong-1** [comment]
检查了一下，是版本变更导致食物的变量名发生了改变，我一会加个临时补丁，晚上再推一版新的把它修了

**Comment by KUROTO-DAN** [comment]
2.26-1版食物背包没崩溃
可是旧存档里的食物在能够使用的时候点了还是「你输入的选项无效，请重试」
此版本中新搓的加胶咖啡能正常给别人使用，但旧存档里自带的加胶咖啡里依旧是「你输入的选项无效，请重试」
测试图：
[image (2).zip](https://github.com/Godofcong-1/erArk/files/14408674/image.2.zip)

**Comment by KUROTO-DAN** [comment]
补充：接上方崩溃后载入auto存档后玩家移动至其他地方后会出现下方报错，要是玩家选用非移动选项则会解发上面的报错
版本信息：2024.2.26-1
最近输入指令：['28', '28', '28', '28', '28', '28', '28', '0', '28', '26', '28', '28', '28', '28', '28', '27', ' [8小时] ', ' [关门] ', '确定\n\n', '0', '博士办公室']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 126, in see_map_flow
  File "Script\UI\Panel\see_map_panel.py", line 200, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\see_map_panel.py", line 233, in move_now
  File "Script\Design\character_move.py", line 43, in own_charcter_move
  File "Script\Design\update.py", line 15, in game_update_flow
  File "Script\Design\character_behavior.py", line 69, in init_character_behavior
  File "Script\Design\character_behavior.py", line 173, in character_behavior
  File "Script\Design\character_behavior.py", line 311, in judge_character_status
UnboundLocalError: local variable 'end_event_id' referenced before assignment
复现存档：
[auto.zip](https://github.com/Godofcong-1/erArk/files/14410067/auto.zip)

**Comment by Godofcong-1** [comment]
没有没有，出现BUG肯定是开发者考虑不够周到，不会是玩家的责任的啦
24点结算的BUG是另一个地方也用到了新版本里食物新增的milk_ml属性，我想想，堵不如疏，我把食物背包本身再改一下，改成自动检测是否有食物是不含这个属性的，有的话就把这个食物重置一遍或者干脆删除。这样点完食物背包，返回再保存覆盖旧存档，应该能把这个BUG永远的解决掉。

**Comment by Godofcong-1** [comment]
新的版本（27-1）已经推上去了，我这边测试的[1.zip] 和 [auto.zip]都正常了，你再试一下看看修好了没

**Comment by KUROTO-DAN** [comment]
这边也好了
