### ISSUE TITLE
BUG 2.28

### ISSUE THREAD

**Issue by Lu-zer** [Godofcong-1/erArk#40]
今天刚下的新版本，开启性爱的指令时的BUG。

版本信息：2024.2.28
最近输入指令：['确定\n\n', '4', '11', '7', '3', '返回', '14', '返回', '1', '下一人', '下一人', '返回', '31', '返回', '3', '11', '返回', '返回', '31', '返回', '性爱']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 42, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 313, in draw
  File "Script\UI\Panel\in_scene_panel.py", line 439, in draw
KeyError: 238

**Comment by Lu-zer** [comment]
应该是只有主角的情况下

**Comment by Godofcong-1** [comment]
请问是建的新档还是读取的旧存档？如果是旧存档的话是哪个版本的？

**Comment by Lu-zer** [comment]
旧的存档，同场景没有NPC，不是触发指令，就是日常不是过滤了猥亵和性爱的指令吗，于是新版本想看看有没有新指令，打开了之后就直接报错了，新存档没问题，我的问题

**Comment by Godofcong-1** [comment]
那可能应该是因为存档太旧了导致的，目前也做了跨版本的存档数据结构更新的机制，不过不确定能最高跨多久，太旧的话可能还不行
