### ISSUE TITLE
【BUG】疑似在同时触发射精阈值与博士/干员任意体力清零退出时会导致游戏崩溃

### ISSUE THREAD

**Issue by qwedc001** [Godofcong-1/erArk#42]
log：
最近输入指令：['208', '208', '208', '208', '208', '208', '208', '208', '208', '208', '208', '208', '208', '208', '208', '208', '208', '208', '208', '208', '208']
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 55, in init
  File "Script\Core\game_init.py", line 45, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 42, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 317, in draw
  File "Script\Core\flow_handle.py", line 274, in askfor_all
  File "Script\Core\flow_handle.py", line 191, in _cmd_deal
  File "Script\Core\flow_handle.py", line 118, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 520, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 4177, in handle_normal_sex
  File "Script\Design\update.py", line 15, in game_update_flow
  File "Script\Design\character_behavior.py", line 61, in init_character_behavior
  File "Script\Design\character_behavior.py", line 148, in character_behavior
  File "Script\Design\character_behavior.py", line 319, in judge_character_status
  File "Script\Design\settle_behavior.py", line 39, in handle_settle_behavior
  File "Script\Design\settle_behavior.py", line 460, in check_second_effect
  File "Script\Design\settle_behavior.py", line 615, in orgasm_effect
  File "Script\UI\Panel\ejaculation_panel.py", line 85, in draw
  File "Script\UI\Panel\ejaculation_panel.py", line 186, in shoot_here
KeyError: -1

操作：邀请H->反复点击正常位->崩溃（疑似是满体力正好反复点击正常位会在触发第三次博士射精时触发此问题）

**Comment by Godofcong-1** [comment]
该问题为精液容积系统还没完全写完导致的过程性BUG，大概等精液流通功能写完了就会自然好了_(:з」∠)_

**Comment by Godofcong-1** [comment]
精液容积系统已暂时告一段落，该BUG应该已经修复，如仍存在欢迎随时反馈
