### ISSUE TITLE
未知错误（该问题已在8月22日版本解决）

### ISSUE THREAD

**Issue by 00590** [Godofcong-1/erArk#65]
[error.log](https://github.com/user-attachments/files/16711145/error.log)

**Comment by TheXeler** [comment]
初步检查了一下error.log，分为两个错误：

### 错误一：Script\UI\Panel\see_map_panel.py 第126行 KeyError
范例：版本信息：2024.8.21-1
最近输入指令：['102', '可露希尔头像', '16', '0', '103', '小满头像', '0', '收藏地点', '5', '12', '0', '收藏地点', '→书\\藏品馆', '96', '内裤', '返回', '2', '返回', '0', '收藏地点', '→宿舍\\1区\\103']
当前游戏内时间：时间:2019年春月14日2点56分
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 59, in init
  File "Script\Core\game_init.py", line 49, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 127, in see_map_flow
  File "Script\UI\Panel\see_map_panel.py", line 126, in draw
KeyError: '1��'

### 错误二：Script\Settle\Second_effect.py 第574行 'CharacterStatusChange'无成员变量'mana_point'
范例：版本信息：2024.8.21-1
最近输入指令：['144', '返回', '33', '九色鹿', '99', '99', '99', '99', '33', '九色鹿', '1', '1', '33', '返回', '16', '33', '返回', '16', '33', '返回', '16']
当前游戏内时间：时间:2019年春月20日0点6分
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 59, in init
  File "Script\Core\game_init.py", line 49, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 43, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 315, in draw
  File "Script\Core\flow_handle.py", line 276, in askfor_all
  File "Script\Core\flow_handle.py", line 193, in _cmd_deal
  File "Script\Core\flow_handle.py", line 120, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 530, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 1208, in handle_wait
  File "Script\Design\update.py", line 15, in game_update_flow
  File "Script\Design\character_behavior.py", line 70, in init_character_behavior
  File "Script\Design\character_behavior.py", line 169, in character_behavior
  File "Script\Design\character_behavior.py", line 424, in judge_character_status
  File "Script\Design\settle_behavior.py", line 41, in handle_settle_behavior
  File "Script\Design\settle_behavior.py", line 523, in check_second_effect
  File "Script\Design\settle_behavior.py", line 550, in second_behavior_effect
  File "Script\Design\talk.py", line 231, in must_show_talk_check
  File "Script\Design\settle_behavior.py", line 328, in return_wrapper
  File "Script\Settle\Second_effect.py", line 574, in handle_down_small_mana_point
AttributeError: type object 'CharacterStatusChange' has no attribute 'mana_point'

问题一已确定是编码问题导致（使用VSCode打开看到Key的值是乱码而报错正常，记事本却看到报错乱码而Key值为"1区"）
注：你看，不用数字ID，屎山了吧.jpg

问题二目前看得一头雾水，也许需要报告者提供存档和复现途径？

**Comment by 00590** [comment]
OK，我也不知道这个“mana”对象是谁，给出列表里完全没找到，跟凭空出来的一样，下面给一下我的大致流程吧*电脑现在不在，没法把日记给出来*
 
版本：8月21的

创建角色*博士*（没错，博士博士）

技能*信息素（直到崩档之前都是初始1级）*平然催眠（级别同上）*透视（收集10个胖次换的）*

点的选项是泌乳和淫乱（啃，这个XP直接这么说出来好尴尬）

初始干员：*兔兔*特雷西娅*凯尔希*可露西尔*华法琳*杜宾*小满*白金*（应该是这些）

然后就是后来招募出的*林*年*九色鹿*

以及来过两次的访客*雪雉*

基建普遍2级，部分3级，中控4级

陷落：白金（好感11000+S评级；100+％信赖；50％催眠）

其余均未陷落

#注：林（好感7500±，A评级；60+％信赖；50％催眠）其余角色或多均有0-10％的催眠进度，*雪雉*和*年*有24-33％催眠进度

然后报错的前一天，*杜宾*被外派，然后从外派之后，先是*睡觉*，然后和*白金*在射击场行了不轨之事，接着平然催眠*林*调戏一番后又和*白金*干坏事，做完将近22点，然后和*九色鹿*聊（催）天（眠），完事后将近0点

#此时时间将近0点，我在此存了个档

此后无论进行什么操作，游戏会发生如下固定显示

*过0点结算
*杜宾委托完成，合成玉+5（有概率载具损坏）
*杜宾的B感觉绝顶了
*杜宾乳喷了/杜宾因为B感觉高潮控制不住乳喷了
*出现”最近输入指令”那一串
*一串报错
*返回到标题界面

#具体的游戏内日记等明天吧

**Comment by TheXeler** [comment]
这里的mana_point指的_应该可能也许大概_ 是指你的射精量表

**Comment by 00590** [comment]
huh……我需要要做一个zip打包上传吗？

**Comment by TheXeler** [comment]
如果可以的话这是最好的了

**Comment by TheXeler** [comment]
如果可以的话这是最好的了

**Comment by Godofcong-1** [comment]
mana_point的BUG在昨天推送的8.22版本中修复了，地点BUG的话需要提供一下存档来复现，看看是什么原因

**Comment by 00590** [comment]
嗨嗨嗨，来了

**Comment by 00590** [comment]
等等……文件太大，仅限25mb

**Comment by 00590** [comment]
我再压缩一下试试吧（）

**Comment by 00590** [comment]
……怎么不支持7z

**Comment by 00590** [comment]
[Uploading 未知错误（第一部分.三次压缩）.zip…]()

**Comment by 00590** [comment]
[Uploading 第二部分.zip…]()

**Comment by 00590** [comment]
[Uploading 第三部分 .zip…]()

**Comment by 00590** [comment]
以上存档文件
*这个github怎么老是更改我的表述*

**Comment by Godofcong-1** [comment]
> 以上存档文件 _这个github怎么老是更改我的表述_

emmm，这三个链接都是跳转到本issue的链接……？

**Comment by 00590** [comment]
我不知道，我发过几次文件，但是都不对

**Comment by 00590** [comment]
> > 以上文档文件_这个github怎么老是更改我的日记_
> 
> emmm，这三个链接都是跳转到本期的链接……？

我知道问题了，文件过大，传不上去

**Comment by Godofcong-1** [comment]
> > > 以上文档文件_这个github怎么老是更改我的日记_
> > 
> > 
> > emmm，这三个链接都是跳转到本期的链接……？
> 
> 我知道问题了，文件过大，传不上去

emmm，要不你加一下项目介绍里的dc群？discord的话，存档大小的文件可以直接发√
