### ISSUE TITLE
8.23版本触发小高潮就报错

### ISSUE THREAD

**Issue by DGgs114** [Godofcong-1/erArk#68]
如题，在触发小高潮时游戏就会报错

版本信息：2024.8.23
最近输入指令：['51', '5', '33', '返回', '33', '自己前去对方位置', '铃兰', '夜烟头像', '铃兰头像', '27', '夜烟头像', '铃兰头像', '猥亵', '4', '2', '返回', '135', '145', '0', '137', '137']
当前游戏内时间：时间:2019年春月2日0点9分
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 59, in init
  File "Script\Core\game_init.py", line 49, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 43, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 315, in draw
  File "Script\Core\flow_handle.py", line 276, in askfor_all
  File "Script\Core\flow_handle.py", line 193, in _cmd_deal
  File "Script\Core\flow_handle.py", line 120, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 530, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 2893, in handle_touch_clitoris
  File "Script\Design\handle_instruct.py", line 158, in chara_handle_instruct_common_settle
  File "Script\Design\update.py", line 15, in game_update_flow
  File "Script\Design\character_behavior.py", line 59, in init_character_behavior
  File "Script\Design\character_behavior.py", line 143, in character_behavior
  File "Script\Design\character_behavior.py", line 424, in judge_character_status
  File "Script\Design\settle_behavior.py", line 45, in handle_settle_behavior
  File "Script\Design\settle_behavior.py", line 523, in check_second_effect
  File "Script\Design\settle_behavior.py", line 563, in second_behavior_effect
KeyError: 997

**Comment by Godofcong-1** [comment]
在8.23-1已修复该问题
