### ISSUE TITLE
报错：外交机制有关

### ISSUE THREAD

**Issue by PhlilpAlapa** [Godofcong-1/erArk#70]
BUG信息：
版本信息：2024.9.4
最近输入指令：['46', '46', '46', '46', '0', '收藏地点', '→中枢\\博士房间', '51', '19', '51', '19', '51', '19', '29', '确定\n\n', '29', '确定\n\n', '0', '11', '29', '确定\n\n']
当前游戏内时间：时间:2019年夏月30日5点11分
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 59, in init
  File "Script\Core\game_init.py", line 49, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 44, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 315, in draw
  File "Script\Core\flow_handle.py", line 276, in askfor_all
  File "Script\Core\flow_handle.py", line 193, in _cmd_deal
  File "Script\Core\flow_handle.py", line 120, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 530, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 1005, in handle_sleep
  File "Script\UI\Panel\normal_panel.py", line 500, in draw
  File "Script\Design\update.py", line 15, in game_update_flow
  File "Script\Design\character_behavior.py", line 76, in init_character_behavior
  File "Script\Design\character_behavior.py", line 997, in update_new_day
  File "Script\UI\Panel\nation_diplomacy_panel.py", line 86, in judge_diplomatic_policy
KeyError: 17

手动定位了一下问题：
nation_diplomacy_panel.py L53
for country_id in cache.rhodes_island.diplomat_of_country:
这个值来自于game_type.py L931
self.diplomat_of_country: Dict[int, Tuple[int, int]] = {}
        """ 负责各的外交官 出身地国家id:[0外交官角色id, 1外交方针id] """
这个id读取的是Birthplace.csv文件里的Id，是国家id
可是，见attr_calculation.py的初始化
    for nation_cid in game_config.config_nation:
        if nation_cid not in country_data.nation_reputation:
            country_data.nation_reputation[nation_cid] = 0
国家声望的键读的是nation_cid,它是势力id，并非国家id

可能的修复方法：
cache.country.nation_reputation[country_id] += up_reputation
改为：
cache.country.nation_reputation[country_id*10+1] += up_reputation

**Comment by Godofcong-1** [comment]
感谢反馈，雀食是这样，已修正

**Comment by PhlilpAlapa** [comment]
版本信息：2024.9.5
最近输入指令：['0', '收藏地点', '→中枢\\博士房间', '51', '19', '51', '19', '51', '19', '29', '确定\n\n', '29', '确定\n\n', '0', '11', '29', '确定\n\n', '0', '收藏地点', '16', '宿舍']
当前游戏内时间：时间:2019年夏月30日5点12分
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 59, in init
  File "Script\Core\game_init.py", line 49, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 128, in see_map_flow
  File "Script\UI\Panel\see_map_panel.py", line 202, in draw
  File "Script\Core\flow_handle.py", line 276, in askfor_all
  File "Script\Core\flow_handle.py", line 193, in _cmd_deal
  File "Script\Core\flow_handle.py", line 120, in run_func
  File "Script\UI\Panel\see_map_panel.py", line 235, in move_now
  File "Script\Design\character_move.py", line 49, in own_charcter_move
  File "Script\Design\update.py", line 15, in game_update_flow
  File "Script\Design\character_behavior.py", line 76, in init_character_behavior
  File "Script\Design\character_behavior.py", line 998, in update_new_day
  File "Script\UI\Panel\nation_diplomacy_panel.py", line 90, in judge_diplomatic_policy
KeyError: 17
现在BUG飞到第90行了
for subordinate_id in game_config.config_nation_data_of_country_subordinate[country_id]
源头是game_config.py的L487
            if now_cid % 10 == 1 and now_cid not in config_nation_data_of_country_subordinate:
                config_nation_data_of_country_subordinate[now_cid] = []
这个cid是势力的cid,但是前面country_id是国家id
改成for subordinate_id in game_config.config_nation_data_of_country_subordinate[nation_cid]就行
属于同一个bug没修完(

**Comment by Godofcong-1** [comment]
出现了一个BUG
修了这一个BUG
请问还剩几个BUG
最上川
