### ISSUE TITLE
error文件内容如下，22号睡到23号时会出现如下报错

### ISSUE THREAD

**Issue by eastcathavefood** [Godofcong-1/erArk#72]
版本信息：2024.9.4
最近输入指令：['0', '男士洗手间', '日常', '猥亵', '猥亵', '0', '休息室', '119', '0', '119', '0', '119', '0', '0', '博士房间', '4', '7', '日常', '29', ' [8小时] ', '确定\n\n']
当前游戏内时间：时间:2019年夏月23日7点35分
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 59, in init
  File "Script\Core\game_init.py", line 49, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 44, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 315, in draw
  File "Script\Core\flow_handle.py", line 276, in askfor_all
  File "Script\Core\flow_handle.py", line 193, in _cmd_deal
  File "Script\Core\flow_handle.py", line 120, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 530, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 1005, in handle_sleep
  File "Script\UI\Panel\normal_panel.py", line 500, in draw
  File "Script\Design\update.py", line 15, in game_update_flow
  File "Script\Design\character_behavior.py", line 76, in init_character_behavior
  File "Script\Design\character_behavior.py", line 997, in update_new_day
  File "Script\UI\Panel\nation_diplomacy_panel.py", line 100, in judge_diplomatic_policy
KeyError: 2

版本信息：2024.9.4
最近输入指令：['16', '16', '16', '16', '16', '16', '16', '16', '16', '16', '16', '0', '16', '→女士洗手间', '16', '16', '0', '博士房间', '29', ' [8小时] ', '确定\n\n']
当前游戏内时间：时间:2019年夏月23日7点54分
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 59, in init
  File "Script\Core\game_init.py", line 49, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 44, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 315, in draw
  File "Script\Core\flow_handle.py", line 276, in askfor_all
  File "Script\Core\flow_handle.py", line 193, in _cmd_deal
  File "Script\Core\flow_handle.py", line 120, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 530, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 1005, in handle_sleep
  File "Script\UI\Panel\normal_panel.py", line 500, in draw
  File "Script\Design\update.py", line 15, in game_update_flow
  File "Script\Design\character_behavior.py", line 76, in init_character_behavior
  File "Script\Design\character_behavior.py", line 997, in update_new_day
  File "Script\UI\Panel\nation_diplomacy_panel.py", line 100, in judge_diplomatic_policy
KeyError: 2

版本信息：2024.9.4
最近输入指令：['0', '男士洗手间', '日常', '猥亵', '猥亵', '0', '休息室', '119', '0', '119', '0', '119', '0', '0', '博士房间', '4', '7', '返回', '日常', '29', '确定\n\n']
当前游戏内时间：时间:2019年夏月23日4点35分
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 59, in init
  File "Script\Core\game_init.py", line 49, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 44, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 315, in draw
  File "Script\Core\flow_handle.py", line 276, in askfor_all
  File "Script\Core\flow_handle.py", line 193, in _cmd_deal
  File "Script\Core\flow_handle.py", line 120, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 530, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 1005, in handle_sleep
  File "Script\UI\Panel\normal_panel.py", line 500, in draw
  File "Script\Design\update.py", line 15, in game_update_flow
  File "Script\Design\character_behavior.py", line 76, in init_character_behavior
  File "Script\Design\character_behavior.py", line 997, in update_new_day
  File "Script\UI\Panel\nation_diplomacy_panel.py", line 100, in judge_diplomatic_policy
KeyError: 2

版本信息：2024.9.4
最近输入指令：['露出', '确定', '露出', '确定', '露出', '返回', '腰技', '确定', '腰技', '返回', '返回', '16', '16', '16', '16', '16', '16', '33', '返回', '27', '36']
当前游戏内时间：时间:2019年夏月23日0点0分
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 59, in init
  File "Script\Core\game_init.py", line 49, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 44, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 315, in draw
  File "Script\Core\flow_handle.py", line 276, in askfor_all
  File "Script\Core\flow_handle.py", line 193, in _cmd_deal
  File "Script\Core\flow_handle.py", line 120, in run_func
  File "Script\UI\Panel\in_scene_panel.py", line 530, in handle_instruct
  File "Script\Design\handle_instruct.py", line 47, in handle_instruct
  File "Script\Design\handle_instruct.py", line 63, in return_wrapper
  File "Script\Design\handle_instruct.py", line 1436, in handle_apologize
  File "Script\Design\handle_instruct.py", line 158, in chara_handle_instruct_common_settle
  File "Script\Design\update.py", line 15, in game_update_flow
  File "Script\Design\character_behavior.py", line 76, in init_character_behavior
  File "Script\Design\character_behavior.py", line 997, in update_new_day
  File "Script\UI\Panel\nation_diplomacy_panel.py", line 100, in judge_diplomatic_policy
KeyError: 2

每当我在19年夏22日睡到23日的时候就会报错，无论前一天或者前两天更换行动都会报错

请问如果这个bug能解决的话可以用546492100这个qq邮箱联系我吗，孩子实在是上不去discord，谢谢大佬，我还可以提供存档文件

**Comment by eastcathavefood** [comment]
破案了，是外交系统有问题，我在外交办里任命了几位干员在其他国家，然后就出现上述报错
