### ISSUE TITLE
存档升级中报错

### ISSUE THREAD

**Issue by assassingyk** [Godofcong-1/erArk#78]
从2024.9.24-2迁移存档到2024.10.21-1，选择读档后显示“开始检测存档的数据结构是否需要跨版本更新”后卡死。
控制台报错如下：
```
Exception in thread flowthread:
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 59, in init
  File "Script\Core\game_init.py", line 49, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\title_flow.py", line 53, in title_panel
  File "Script\UI\Panel\see_save_info_panel.py", line 71, in draw
  File "Script\Core\flow_handle.py", line 276, in askfor_all
  File "Script\Core\flow_handle.py", line 193, in _cmd_deal
  File "Script\Core\flow_handle.py", line 120, in run_func
  File "Script\UI\Panel\see_save_info_panel.py", line 200, in draw_save_handle
  File "Script\Core\flow_handle.py", line 276, in askfor_all
  File "Script\Core\flow_handle.py", line 193, in _cmd_deal
  File "Script\Core\flow_handle.py", line 120, in run_func
  File "Script\UI\Panel\see_save_info_panel.py", line 207, in load_save
  File "Script\Core\save_handle.py", line 162, in input_load_save
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "Script\Core\game_init.py", line 104, in _init
  File "Script\Core\game_init.py", line 75, in init
  File "Script\Core\save_handle.py", line 60, in establish_save
  File "Script\Core\save_handle.py", line 74, in establish_save_linux
KeyError: 0

```

**Comment by Godofcong-1** [comment]
感谢反馈，10.22已修正

**Comment by assassingyk** [comment]
emmmm, 2024.10.23版本加载老存档依然报错（
`
版本信息：2024.10.23
最近输入指令：['117', '返回', '0', '凝思庭', '28', '36', '26', '\n速冻宫保羽兽丁_199', '0', '收藏地点', '→中枢\\博士办公室', '81', '暴雨头像', '23', '槐琥头像', '阿米娅头像', '槐琥头像', '5', '0', '1', '0']
当前游戏内时间：时间:2019年夏月6日17点5分
Traceback (most recent call last):
  File "Script\Core\game_init.py", line 59, in init
  File "Script\Core\game_init.py", line 49, in run_main_flow
  File "Script\Design\start_flow.py", line 16, in start_frame
  File "Script\Design\handle_panel.py", line 18, in return_wrapper
  File "Script\UI\Flow\normal_flow.py", line 46, in in_scene_flow
  File "Script\UI\Panel\in_scene_panel.py", line 144, in draw
  File "Script\UI\Panel\see_character_info_panel.py", line 570, in __init__
  File "Script\Design\handle_premise.py", line 27, in return_wrapper
  File "Script\Design\handle_premise.py", line 14181, in handle_self_orgasm_edge
AttributeError: 'BODY_H_STATE' object has no attribute 'orgasm_edge'`

**Comment by assassingyk** [comment]
pull 了一下最新版，还是有报错，看起来是新加的寸止系统的问题（？
```
版本信息：2024.10.23-1
最近输入指令：['117', '返回', '0', '凝思庭', '28', '36', '26', '\n速冻宫保羽兽丁_199', '0', '收藏地点', '→中枢\\博士办公室', '81', '暴雨头像', '23', '槐琥头像', '阿米娅头像', '槐琥头像', '5', '0', '1', '0']
当前游戏内时间：时间:2019年夏月6日17点5分
Traceback (most recent call last):
  File "F:\File\hx\Game\era\erArk\Script\Core\game_init.py", line 59, in init
    run_main_flow()
  File "F:\File\hx\Game\era\erArk\Script\Core\game_init.py", line 49, in run_main_flow
    main_flow()
  File "F:\File\hx\Game\era\erArk\Script\Design\start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File "F:\File\hx\Game\era\erArk\Script\Design\handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File "F:\File\hx\Game\era\erArk\Script\UI\Flow\normal_flow.py", line 46, in in_scene_flow
    now_panel.draw()
  File "F:\File\hx\Game\era\erArk\Script\UI\Panel\in_scene_panel.py", line 144, in draw
    character_head_draw = see_character_info_panel.CharacterInfoHead(
  File "F:\File\hx\Game\era\erArk\Script\UI\Panel\see_character_info_panel.py", line 570, in __init__
    if handle_premise.handle_self_orgasm_edge(character_id):
  File "F:\File\hx\Game\era\erArk\Script\Design\handle_premise.py", line 27, in return_wrapper
    return func(*args, **kwargs)
  File "F:\File\hx\Game\era\erArk\Script\Design\handle_premise.py", line 14181, in handle_self_orgasm_edge
    return character_data.h_state.orgasm_edge == 1
AttributeError: 'BODY_H_STATE' object has no attribute 'orgasm_edge'. Did you mean: 'orgasm_level'?
```

**Comment by assassingyk** [comment]
稍微调试了下，似乎是刀客塔本身的character_data各种数据类型没正确更新？报错时的character_id是0，尝试注释掉orgasm_level这段判断继续往下推，只要和角色互动也会遇到类似的缺属性报错（
```
Traceback (most recent call last):
  File " ***\erArk\Script\Core\game_init.py", line 59, in init
    run_main_flow()
  File " ***\erArk\Script\Core\game_init.py", line 49, in run_main_flow
    main_flow()
  File " ***\erArk\Script\Design\start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File " ***\erArk\Script\Design\handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File " ***\erArk\Script\UI\Flow\normal_flow.py", line 46, in in_scene_flow
    now_panel.draw()
  File " ***\erArk\Script\UI\Panel\in_scene_panel.py", line 316, in draw
    flow_handle.askfor_all(ask_list)
  File " ***\erArk\Script\Core\flow_handle.py", line 276, in askfor_all
    _cmd_deal(order)
  File " ***\erArk\Script\Core\flow_handle.py", line 193, in _cmd_deal
    cmd_map[order_number]()
  File " ***\erArk\Script\Core\flow_handle.py", line 120, in run_func
    cmd_func(*arg, **kw)
  File " ***\erArk\Script\UI\Panel\in_scene_panel.py", line 564, in handle_instruct
    handle_instruct.handle_instruct(instruct_id)
  File " ***\erArk\Script\Design\handle_instruct.py", line 47, in handle_instruct
    constant.handle_instruct_data[instruct]()
  File " ***\erArk\Script\Design\handle_instruct.py", line 63, in return_wrapper
    return func(*args, **kwargs)
  File " ***\erArk\Script\Design\handle_instruct.py", line 279, in handle_chat
    chara_handle_instruct_common_settle(constant.CharacterStatus.STATUS_CHAT)
  File " ***\erArk\Script\Design\handle_instruct.py", line 162, in chara_handle_instruct_common_settle
    update.game_update_flow(duration)
  File " ***\erArk\Script\Design\update.py", line 15, in game_update_flow
    character_behavior.init_character_behavior()
  File " ***\erArk\Script\Design\character_behavior.py", line 60, in init_character_behavior
    character_behavior(0, cache.game_time, pl_start_time)
  File " ***\erArk\Script\Design\character_behavior.py", line 152, in character_behavior
    judge_character_status(character_id)
  File " ***\erArk\Script\Design\character_behavior.py", line 435, in judge_character_status
    start_event_draw = event.handle_event(character_id, event_before_instrust_flag = True)
  File " ***\erArk\Script\Design\event.py", line 72, in handle_event
    if character_data.event.chara_diy_event_flag:
AttributeError: 'Chara_Event' object has no attribute 'chara_diy_event_flag'
```
不和角色互动直接睡觉报另一个错
```
Traceback (most recent call last):
  File " ***\erArk\Script\Core\game_init.py", line 59, in init
    run_main_flow()
  File " ***\erArk\Script\Core\game_init.py", line 49, in run_main_flow
    main_flow()
  File " ***\erArk\Script\Design\start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File " ***\erArk\Script\Design\handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File " ***\erArk\Script\UI\Flow\normal_flow.py", line 46, in in_scene_flow
    now_panel.draw()
  File " ***\erArk\Script\UI\Panel\in_scene_panel.py", line 316, in draw
    flow_handle.askfor_all(ask_list)
  File " ***\erArk\Script\Core\flow_handle.py", line 276, in askfor_all
    _cmd_deal(order)
  File " ***\erArk\Script\Core\flow_handle.py", line 193, in _cmd_deal
    cmd_map[order_number]()
  File " ***\erArk\Script\Core\flow_handle.py", line 120, in run_func
    cmd_func(*arg, **kw)
  File " ***\erArk\Script\UI\Panel\in_scene_panel.py", line 564, in handle_instruct
    handle_instruct.handle_instruct(instruct_id)
  File " ***\erArk\Script\Design\handle_instruct.py", line 47, in handle_instruct
    constant.handle_instruct_data[instruct]()
  File " ***\erArk\Script\Design\handle_instruct.py", line 63, in return_wrapper
    return func(*args, **kwargs)
  File " ***\erArk\Script\Design\handle_instruct.py", line 1006, in handle_sleep
    now_draw.draw()
  File " ***\erArk\Script\UI\Panel\normal_panel.py", line 511, in draw
    update.game_update_flow(self.sleep_time_min)
  File " ***\erArk\Script\Design\update.py", line 15, in game_update_flow
    character_behavior.init_character_behavior()
  File " ***\erArk\Script\Design\character_behavior.py", line 60, in init_character_behavior
    character_behavior(0, cache.game_time, pl_start_time)
  File " ***\erArk\Script\Design\character_behavior.py", line 152, in character_behavior
    judge_character_status(character_id)
  File " ***\erArk\Script\Design\character_behavior.py", line 448, in judge_character_status
    first_settle_panel = settle_behavior.handle_settle_behavior(character_id, end_time, event_type_now)
  File " ***\erArk\Script\Design\settle_behavior.py", line 40, in handle_settle_behavior
    constant.settle_behavior_effect_data[effect_id](character_id, add_time, change_data, now_time)
  File " ***\erArk\Script\Design\settle_behavior.py", line 321, in return_wrapper
    return func(*args, **kwargs)
  File " ***\erArk\Script\Settle\default_cloth.py", line 458, in handle_get_sleep_cloth
    if handle_premise.handle_ask_not_wear_cloth_in_sleep(character_id):
  File " ***\erArk\Script\Design\handle_premise.py", line 27, in return_wrapper
    return func(*args, **kwargs)
  File " ***\erArk\Script\Design\handle_premise.py", line 18252, in handle_ask_not_wear_cloth_in_sleep
    return character_data.body_manage[4]
AttributeError: 'Character' object has no attribute 'body_manage'
```

**Comment by assassingyk** [comment]
哦，我好像看到问题了，加载存档和更新存档里面有一句把刀客塔本身的character_data数据类型更新跳过去了，应该是需要改下这边）
```
       if value.cid == 0:
            continue
```

**Comment by Godofcong-1** [comment]
> 哦，我好像看到问题了，加载存档和更新存档里面有一句把刀客塔本身的character_data数据类型更新跳过去了，应该是需要改下这边）
> 
> https://github.com/Godofcong-1/erArk/blob/6ff227b64cfe1ace55f378454efe9194e43492d7/Script/Core/save_handle.py#L158-L159

啊，这个是我debug的时候加上的，de完忘记删了_(:з」∠)_
