### ISSUE TITLE
选择初期干员时重置选择会报错

### ISSUE THREAD

**Issue by assassingyk** [Godofcong-1/erArk#79]
略难绷的bug）
```
版本信息：2024.10.25
最近输入指令：[ '0', '0', 'aaa', '选择初期干员', '63', '65', '80', ' [重置选择] ']
当前游戏内时间：时间:2019年春月1日6点0分
Traceback (most recent call last):
  File " ***\erArk\Script\Core\game_init.py", line 59, in init
    run_main_flow()
  File " ***\erArk\Script\Core\game_init.py", line 49, in run_main_flow
    main_flow()
  File " ***\erArk\Script\Design\start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File " ***\erArk\Script\Design\handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File " ***\erArk\Script\UI\Flow\creator_character_flow.py", line 44, in creator_character_panel
    if confirm_character_attr_panel():
  File " ***\erArk\Script\UI\Flow\creator_character_flow.py", line 122, in confirm_character_attr_panel
    yrn = flow_handle.askfor_all(ask_list)
  File " ***\erArk\Script\Core\flow_handle.py", line 276, in askfor_all
    _cmd_deal(order)
  File " ***\erArk\Script\Core\flow_handle.py", line 193, in _cmd_deal
    cmd_map[order_number]()
  File " ***\erArk\Script\Core\flow_handle.py", line 120, in run_func
    cmd_func(*arg, **kw)
  File " ***\erArk\Script\UI\Flow\creator_character_flow.py", line 632, in select_npc
    yrn = flow_handle.askfor_all(return_list)
  File " ***\erArk\Script\Core\flow_handle.py", line 276, in askfor_all
    _cmd_deal(order)
  File " ***\erArk\Script\Core\flow_handle.py", line 193, in _cmd_deal
    cmd_map[order_number]()
  File " ***\erArk\Script\Core\flow_handle.py", line 120, in run_func
    cmd_func(*arg, **kw)
  File " ***\erArk\Script\UI\Flow\creator_character_flow.py", line 781, in reset_select
    self.prepare_filter()
  File " ***\erArk\Script\UI\Flow\creator_character_flow.py", line 668, in prepare_filter
    self.race_filter_id_dict[race_name].append(NPC_id)
KeyError: '博士'
```

**Comment by Godofcong-1** [comment]
已修正，感谢反馈
