### ISSUE TITLE
加载旧版本存档后报错

### ISSUE THREAD

**Issue by assassingyk** [Godofcong-1/erArk#89]
~~是新的时间逻辑改了之后没做存档层面的调整吗~~
不对，看了下新开游戏一样会炸，那应该单纯就是tem_date那边变量没定义好(
```
版本信息：2024.11.8
最近输入指令：['下一页', '下一页', '下一页', '下一页', '0', '7', '生娱', '食堂', '0', '取餐区', '0', '酒吧', '1', '返回', '5', '9', '1', '0', '1', '返回', '36']
当前游戏内时间：时间:2019年秋月15日18点21分
Traceback (most recent call last):
  File " ***\erArk\Script\Core\game_init.py", line 59, in init
    run_main_flow()
  File " ***\erArk\Script\Core\game_init.py", line 49, in run_main_flow
    main_flow()
  File " ***\erArk\Script\Design\start_flow.py", line 16, in start_frame
    constant.panel_data[cache.now_panel_id]()
  File " ***\erArk\Script\Design\handle_panel.py", line 18, in return_wrapper
    return func(*args, **kwargs)
  File " ***\erArk\Script\UI\Flow\normal_flow.py", line 46, in in_scene_flow
    now_panel.draw()
  File " ***\erArk\Script\UI\Panel\in_scene_panel.py", line 321, in draw
    flow_handle.askfor_all(ask_list)
  File " ***\erArk\Script\Core\flow_handle.py", line 276, in askfor_all
    _cmd_deal(order)
  File " ***\erArk\Script\Core\flow_handle.py", line 193, in _cmd_deal
    cmd_map[order_number]()
  File " ***\erArk\Script\Core\flow_handle.py", line 120, in run_func
    cmd_func(*arg, **kw)
  File " ***\erArk\Script\UI\Panel\in_scene_panel.py", line 590, in handle_instruct
    handle_instruct.handle_instruct(instruct_id)
  File " ***\erArk\Script\Design\handle_instruct.py", line 47, in handle_instruct
    constant.handle_instruct_data[instruct]()
  File " ***\erArk\Script\Design\handle_instruct.py", line 63, in return_wrapper
    return func(*args, **kwargs)
  File " ***\erArk\Script\Design\handle_instruct.py", line 1391, in handle_followed
    update.game_update_flow(5)
  File " ***\erArk\Script\Design\update.py", line 14, in game_update_flow
    game_time.sub_time_now(add_time)
  File " ***\erArk\Script\Design\game_time.py", line 168, in sub_time_now
    cache.game_time = tem_date
UnboundLocalError: local variable 'tem_date' referenced before assignment
```

**Comment by Godofcong-1** [comment]
雀食手滑了，已紧急推送11.8-1版本
